name: just_chat
description: "A simple chat application."

publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.0.2
  cloudinary_api: ^1.1.1
  cloudinary_url_gen: ^1.8.0
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_storage: ^13.0.2
  flutter:
    sdk: flutter
  go_router: ^16.2.1
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
